### ISSUE TITLE
Error While Connecting a Device : "Error: Unknown input." 

### ISSUE THREAD

**Issue by salmanfarisvp** [hkayann/node-red-contrib-ble-sense#3]
First of thanks for the node, I'm using this with raspberry pi and trying to read sensor value from a silicon lab dev board. 

also noticed that, it's not outputting anything on debug window when we scan. 

I used example flow, and changed that MAC as per the device address. 

![image](https://user-images.githubusercontent.com/11945360/133063500-26d1d4c8-1261-41be-9911-70c90ef2ce85.png)

**Comment by hkayann** [comment]
Hi @salmanfarisvp,

You should start scanning, while it is scanning, you should insert your MAC address. Have you done like that?

**Comment by salmanfarisvp** [comment]
Hi @hkayann , Thanks for the swift replay, Sorry Where should I insert the MAC?

**Comment by hkayann** [comment]
Your setup is correct. You should scan with `BLE Scanner`. While it is scanning, you should insert your MAC to `BLE Connect`.

**Comment by salmanfarisvp** [comment]
Thanks @hkayann , 

Now I am getting. 
![image](https://user-images.githubusercontent.com/11945360/133067312-989f2bc1-8ed8-4551-94ef-92acfaa7e062.png)
 
Here is my config 

![image](https://user-images.githubusercontent.com/11945360/133067398-e6204c5c-4af8-4754-a881-310afeb6b274.png)

**Comment by hkayann** [comment]
This means that your **peripheral (silicon lab dev board)** is not allowing subscriptions. You need to fix the code/setting on your peripheral, it is not related to nodes/Pi.

**Comment by salmanfarisvp** [comment]
But I can easily read the same service with a mobile phone!

**Comment by hkayann** [comment]
Mobile applications like `nRF Connect` can bypass that one I guess. These nodes are mainly created for getting data from microcontrollers like `Arduino Nano 33 BLE Sense`. From the arduino/peripheral side, I am allowing subscriptions via `BLEShortCharacteristic temperatureCharacteristic( BLE_UUID_TEMPERATURE, BLERead | BLENotify );`. Here `BLENotify` allows subscribing to that certain characteristic.

If you have a similar thing, please have a look how you can allow that, because I am sure, there is nothing we can do from node/central side. If the issue persists it might worth to ask it in stackoverflow.com as well.

**Comment by hkayann** [comment]
I am closing as this should be handled from peripheral's side.

**Comment by salmanfarisvp** [comment]
Thanks @hkayann
